services:
  - type: worker
    name: contest-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: "8600057182:AAGImzI3A7IjGSoEPT2JUpg2-QJ1ukNkbAA"
      - key: ADMIN_ID
        value: "6599083480"
